### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by vdobro** [rastersoft/autovala-atom#1]
How this happened:

1. Installed the autovala-atom package from the git repository
2. Launched Atom and saw the error:

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [autovala-atom](https://github.com/rastersoft/autovala-atom) package 0.5.0

### Stack Trace

Failed to load the autovala-atom package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autovala-atom/lib/treeview.coffee:1:29)
    at /packages/autovala-atom/lib/treeview.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autovala-atom/lib/autovala-atom.coffee:2:14)
    at /packages/autovala-atom/lib/autovala-atom.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
autocomplete-haskell 0.6.7 
autovala-atom 0.5.0 
busy 0.7.0 
haskell-ghc-mod 1.19.4 
ide-haskell 1.8.2 
ide-haskell-cabal 1.7.5 
language-haskell 1.12.1 
language-vala 0.2.0 
material-ui 1.0.9 
project-manager 3.3.3 
```

**Comment by rastersoft** [comment]
It seems that finally they deprecated "atom-space-pen-views"... I have to find a way to replace the views... :(

**Comment by rastersoft** [comment]
I forgot that you must run "apm install" after installing a package to install those dependencies. Try running it from a command line and everything should run fine (but don't forget to close and open again Atom).
